services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: surveydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - surveydb_data:/var/lib/postgresql/data
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app/app
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/surveydb
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  surveydb_data:
